# Generated by Django 2.2.16 on 2020-12-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile')),
            ],
        ),
    ]
