# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_risks', '0049_auto_20190918_1242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riskapp',
            table='risks_riskapp',
        ),
    ]
