# Generated by Django 2.2.24 on 2022-03-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("layers", "0035_auto_20220223_1547"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offerings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="layers.Layer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offering",
                "verbose_name_plural": "Offerings",
            },
        ),
        migrations.CreateModel(
            name="FeatureOfInterest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="layers.Layer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature of interest",
                "verbose_name_plural": "Features of interest",
            },
        ),
    ]
