# Generated by Django 2.2.24 on 2022-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_sos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureofinterest",
            name="definition",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="value",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="definition",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="value",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
