# Generated by Django 2.2.24 on 2022-03-08 13:44
#########################################################################
#
# Copyright (C) 2022 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_sos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureofinterest",
            name="definition",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="value",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="definition",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offerings",
            name="value",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
