# Generated by Django 2.2.24 on 2022-04-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureOfInterest',
        ),
    ]
