# Generated by Django 2.2.24 on 2022-03-24 14:39
#########################################################################
#
# Copyright (C) 2022 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_sos", "0002_auto_20220308_1344"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featureofinterest",
            old_name="definition",
            new_name="code_space",
        ),
        migrations.RenameField(
            model_name="featureofinterest",
            old_name="value",
            new_name="sampled_feature",
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="featureofinterest",
            name="geometry_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
