# Generated by Django 2.2.24 on 2022-03-24 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0002_auto_20220308_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureofinterest',
            old_name='definition',
            new_name='code_space',
        ),
        migrations.RenameField(
            model_name='featureofinterest',
            old_name='value',
            new_name='sampled_feature',
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='geometry_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
