# Generated by Django 2.2.24 on 2022-03-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0003_auto_20220324_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureofinterest',
            old_name='code_space',
            new_name='codespace',
        ),
    ]
