# Generated by Django 2.2.24 on 2022-03-24 14:41
#########################################################################
#
# Copyright (C) 2022 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_sos", "0003_auto_20220324_1439"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featureofinterest",
            old_name="code_space",
            new_name="codespace",
        ),
    ]
