# Generated by Django 2.2.24 on 2022-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0005_auto_20220324_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureofinterest',
            name='identifier',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
