# Generated by Django 2.2.24 on 2022-03-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0006_featureofinterest_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureofinterest',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='feature_id',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='feature_type',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='srs_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
