# Generated by Django 2.2.24 on 2022-03-29 11:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0007_auto_20220329_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureofinterest',
            name='geometry_type',
        ),
        migrations.AddField(
            model_name='featureofinterest',
            name='shape_blob',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='featureofinterest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
