# Generated by Django 2.2.24 on 2022-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0008_auto_20220329_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureofinterest',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='featureofinterest',
            name='shape_blob',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
