# Generated by Django 2.2.24 on 2022-03-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_auto_20201012_0931'),
        ('geonode_sos', '0009_auto_20220329_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('site', models.CharField(max_length=2000, null=True)),
                ('individual_name', models.CharField(max_length=2000, null=True)),
                ('position_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('delivery_point', models.CharField(max_length=255, null=True)),
                ('administrative_area', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Service')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Provider',
            },
        ),
    ]
