# Generated by Django 2.2.24 on 2022-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0010_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
