# Generated by Django 2.2.24 on 2022-03-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0035_auto_20220223_1547'),
        ('geonode_sos', '0012_auto_20220330_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('delivery_point', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('administrative_area', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('online_resource', models.CharField(max_length=2000, null=True)),
                ('definition', models.CharField(max_length=2000, null=True)),
                ('contact_type', models.CharField(choices=[('manufacturer', 'manufacturer'), ('owner', 'owner'), ('pointOfContact', 'pointOfContact')], max_length=2000, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
    ]
