# Generated by Django 2.2.24 on 2022-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0013_sensorresponsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorresponsible',
            old_name='definition',
            new_name='arcrole',
        ),
        migrations.RemoveField(
            model_name='sensorresponsible',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='sensorresponsible',
            name='extracted_arcrole',
            field=models.CharField(choices=[('manufacturer', 'manufacturer'), ('owner', 'owner'), ('pointOfContact', 'pointOfContact')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensorresponsible',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
