# Generated by Django 2.2.24 on 2022-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_sos', '0015_auto_20220330_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorresponsible',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
