# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralizedServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(help_text=b'Centralized Server IP address.')),
                ('port', models.IntegerField(help_text=b'Centralized Server TCP port number.')),
                ('interval', models.IntegerField(default=3600, help_text=b'Data aggregation time interval (in seconds).')),
                ('db_path', models.CharField(blank=True, default=b'logstash.db', help_text=b'The local SQLite database to cache log events between emitting and transmission to the Logstash server. This way log events are cached even across process restarts (and crashes).', max_length=500, null=True)),
                ('socket_timeout', models.FloatField(blank=True, default=5.0, help_text=b'Timeout in seconds for TCP connections.', null=True)),
                ('queue_check_interval', models.FloatField(blank=True, default=2.0, help_text=b'Interval in seconds to check the internal queue for new messages to be cached in the database.', null=True)),
                ('queue_events_flush_interval', models.FloatField(blank=True, default=0.1, help_text=b'Interval in seconds to send cached events from the database to Logstash.', null=True)),
                ('queue_events_flush_count', models.IntegerField(blank=True, default=50, help_text=b'Count of cached events to send from the database to Logstash; events are sent to Logstash whenever QUEUED_EVENTS_FLUSH_COUNT or QUEUED_EVENTS_FLUSH_INTERVAL is reached, whatever happens first.', null=True)),
                ('queue_events_batch_size', models.IntegerField(blank=True, default=50, help_text=b'Maximum number of events to be sent to Logstash in one batch. Depending on the transport, this usually means a new connection to the Logstash is established for the event batch.', null=True)),
                ('logstash_db_timeout', models.FloatField(blank=True, default=5.0, help_text=b"Timeout in seconds to 'connect' the SQLite database.", null=True)),
                ('last_successful_deliver', models.DateTimeField(blank=True, help_text=b'Timestamp of the last successful deliver.', null=True)),
                ('next_scheduled_deliver', models.DateTimeField(blank=True, help_text=b'Timestamp of the next scheduled deliver.', null=True)),
                ('last_failed_deliver', models.DateTimeField(blank=True, help_text=b'Timestamp of the last failed deliver.', null=True)),
            ],
        ),
    ]
