# Generated by Django 2.2.13 on 2020-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_logstash', '0002_auto_20191209_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedserver',
            name='db_path',
            field=models.CharField(blank=True, default='logstash_7ce05edd.db', help_text='The local SQLite database to cache log events between emitting and transmission to the Logstash server. This way log events are cached even across process restarts (and crashes).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='host',
            field=models.CharField(help_text='Centralized Server IP address/Host name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='interval',
            field=models.IntegerField(default=3600, help_text='Data aggregation time interval (in seconds).'),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='last_failed_deliver',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last failed deliver.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='last_successful_deliver',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful deliver.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='local_ip',
            field=models.GenericIPAddressField(help_text='Local Server IP address.', protocol='ipv4'),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='logstash_db_timeout',
            field=models.FloatField(blank=True, default=5.0, help_text="Timeout in seconds to 'connect' the SQLite database.", null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='next_scheduled_deliver',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the next scheduled deliver.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='port',
            field=models.IntegerField(help_text='Centralized Server TCP port number.'),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='queue_check_interval',
            field=models.FloatField(blank=True, default=2.0, help_text='Interval in seconds to check the internal queue for new messages to be cached in the database.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='queue_events_batch_size',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum number of events to be sent to Logstash in one batch. Depending on the transport, this usually means a new connection to the Logstash is established for the event batch.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='queue_events_flush_count',
            field=models.IntegerField(blank=True, default=10, help_text='Count of cached events to send from the database to Logstash; events are sent to Logstash whenever QUEUED_EVENTS_FLUSH_COUNT or QUEUED_EVENTS_FLUSH_INTERVAL is reached, whatever happens first.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='queue_events_flush_interval',
            field=models.FloatField(blank=True, default=0.1, help_text='Interval in seconds to send cached events from the database to Logstash.', null=True),
        ),
        migrations.AlterField(
            model_name='centralizedserver',
            name='socket_timeout',
            field=models.FloatField(blank=True, default=20.0, help_text='Timeout in seconds for TCP connections.', null=True),
        ),
    ]
