# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_logstash', '0004_auto_20200425_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedserver',
            name='db_path',
            field=models.CharField(blank=True, default=b'logstash_2e79e3b1.db', help_text=b'The local SQLite database to cache log events between emitting and transmission to the Logstash server. This way log events are cached even across process restarts (and crashes).', max_length=500, null=True),
        ),
    ]
