
from geonode.settings import *

KEYCLOAK_HOST_URL=''
KEYCLOAK_CLIENT=''
KEYCLOAK_CLIENT_SECRET=''
KEYCLOAK_GRANT_TYPE=''
KEYCLOAK_SCOPE=''
KEYCLOAK_REALM=''
KEYCLOAK_CLIENT_ID=''

INSTALLED_APPS += ('keycloakrole',)
